services:
  - type: web
    name: mesa-facil-gestao-saas
    env: node
    plan: free
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: "18.19.0"
